### ISSUE TITLE
Remove `secret_key_base`

### ISSUE THREAD

**Issue by juandazapata** [nebulab/nova#3]
This is too sensitive to be committed to the repo. It should be handled in an `env var`, or as part of a setup task. An incautious user could just left this value unchanged, accidentally exposing itself to a vulnerability. This should be unique per each installation.

https://github.com/nebulab/gcommerce/blob/master/config/config.exs#L12

**Comment by apeacox** [comment]
Hi @juandazapata , thank you for pointing this out :-)

You're right, in _normal conditions_ this should be a serious security issue, however, it isn't when it comes to production environments, because `config/prod.exs` loads `config/prod.secret.exs` which (actually) isn't tracked by the version control. In that file you'll have something like this:

```
config :nova, Nova.Endpoint,
  secret_key_base: System.get_env("NOVA_SECRET_KEY_BASE")

# Configure your database
config :nova, Nova.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: System.get_env("NOVA_DB_USER"),
  password: System.get_env("NOVA_DB_PASSWORD"),
  database: "nova_prod",
  pool_size: 20
```

which means:
1. You can add this file to git, without sharing `prod` secrets
2. You don't have to worry about `dev` and `test` secrets

This is also the suggested approach from the [Phoenix guides](http://www.phoenixframework.org/docs/heroku#section-making-our-project-heroku-ready). With this approach, we can safely use `config/prod.exs` without concerns :-)

As a side note, my first attempt was to integrate [dotenv_elixir](https://github.com/avdi/dotenv_elixir) to easily keep all envs in a dotfile, but it doesn't work inside Mix; see [this discussion](https://groups.google.com/forum/#!topic/elixir-lang-core/SLlJxiMa-7Q) for more details.
